# -*- coding: utf-8 -*-
"""突變檢查：證明純邏輯測試有鑑別力——把實作故意改壞，對應的測試必須變紅。

用法（repo 根目錄）： python Tools/DotnetCheck/mutation_check.py
需要 .NET 8 SDK（預設找 %LOCALAPPDATA%\\Microsoft\\dotnet\\dotnet.exe，否則用 PATH 上的 dotnet）。

每個突變：改檔 → 完整重編 → 跑測試 → 記下變紅的測試 → 還原。
還原一律「重寫原內容」而不是複製備份檔：保留舊修改時間會讓 MSBuild 增量編譯沿用突變後的 binary 而誤報。
結束碼：全部突變都被抓到且還原後全綠 = 0，否則 = 1。
"""
import io
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PROJ = os.path.join(ROOT, "Tools", "DotnetCheck", "PureLogic.Tests", "PureLogic.Tests.csproj")
LOGIC = "Assets/Scripts/Core/Logic/"
INPUT = "Assets/Scripts/Input/"

_local = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Microsoft", "dotnet", "dotnet.exe")
DOTNET = _local if os.path.isfile(_local) else "dotnet"
ENV = dict(os.environ, DOTNET_CLI_TELEMETRY_OPTOUT="1", DOTNET_NOLOGO="1", DOTNET_CLI_UI_LANGUAGE="en")

# (代號, 說明, 檔案, 原文, 改壞後, 至少要變紅的測試)
MUTATIONS = [
    ("M1", "衰減表失效（三次都滑 1.4m）", LOGIC + "CombatTuning.cs",
     "public float[] DashDistances = { 1.4f, 0.9f, 0.5f };",
     "public float[] DashDistances = { 1.4f, 1.4f, 1.4f };",
     "ThreeChainedDashes_Decay_1_4_Then_0_9_Then_0_5_Total_2_8"),
    ("M2", "切後搖可縮短攻擊週期（紅線 2）", LOGIC + "HeroCombatBrain.cs",
     "if (_body.TryBeginCadenceDash(dirX, dirZ)) SetState(PlayerState.CadenceDashing);",
     "if (_body.TryBeginCadenceDash(dirX, dirZ)) { SetState(PlayerState.CadenceDashing); _nextAttackReadyTime = _clock; }",
     "DashCancellingEveryHit_NeverShortensAttackPeriod"),
    ("M3", "預輸入緩衝沒有 120ms 時限", LOGIC + "HeroCombatBrain.cs",
     "if (_clock - _bufferedFlickTime <= _tuning.InputBufferSeconds)", "if (true)",
     "FlickOlderThan120msBeforeHit_IsDiscarded"),
    ("M4", "收招／滑步中拒收移動指令（卡刀，紅線 1）", LOGIC + "HeroCombatBrain.cs",
     "                case PlayerState.AttackRecovery:\n                case PlayerState.CadenceDashing:\n"
     "                    SetPendingMove(destination);\n                    break;",
     "                case PlayerState.AttackRecovery:\n                case PlayerState.CadenceDashing:\n"
     "                    break;",
     "MoveCommand_IsHonouredFromEveryPhase1State"),
    ("M5", "狀態機放行所有轉換", LOGIC + "PlayerStateMachine.cs",
     "return (AllowedMask[f] & (1 << t)) != 0;", "return true;",
     "IllegalTransitions_AreRejected_StateAndEventsUntouched"),
    ("M6", "0 充能仍可滑步", LOGIC + "CadenceSim.cs",
     "if (state.Charges <= 0)\n                {", "if (state.Charges < -99)\n                {",
     "Charges_CapAtThree_RejectAtZero_RecoverEvery2_5s"),
    ("M7", "邊緣死區不含底邊", LOGIC + "GestureMath.cs",
     "return x < marginPixels || x > screenWidth - marginPixels || y < marginPixels;",
     "return x < marginPixels || x > screenWidth - marginPixels;",
     "EdgeDeadzone_RejectsLeftRightBottom_Within8px"),
    ("M8", "射程內改鎖會重新起手（審查 r1 M-5）", LOGIC + "HeroCombatBrain.cs",
     "                        _currentTarget = target;\n                        _body.FaceTarget(target);\n                        return;",
     "                        _currentTarget = target;\n                        EngageCurrentTarget();\n                        return;",
     "AlternatingBetweenTwoTargets_DoesNotStallTheAttack"),
    ("R1", "切模式時直接釋放槽位（審查 r1 M-1）", INPUT + "TouchGestureRouter.cs",
     "                    if (!_slotUsed[i]) continue;\n                    _slotRoute[i] = TouchRoute.Rejected;\n"
     "                    _trackers[i].Cancel();",
     "                    _slotUsed[i] = false;",
     "SwitchingMode_WhileAFingerIsStillDown_DoesNotConjureAWorldTap"),
    ("R2", "只記得一根已結束手指（審查 r1 M-2）", INPUT + "TouchGestureRouter.cs",
     "private const int EndedHistorySize = MaxTouches;", "private const int EndedHistorySize = 1;",
     "TwoFingersEndingInTheSameFrame_NeitherIsReplayedAsANewTap"),
    ("R3", "微輪盤離手補發點擊（高壓紅線）", INPUT + "TouchGestureRouter.cs",
     "                case TouchRoute.Pip:\n                    _pip.End();\n                    break;\n\n"
     "                case TouchRoute.UiRegion:",
     "                case TouchRoute.Pip:\n                    _pip.End();\n                    _sink.OnWorldTap(x, y);\n"
     "                    break;\n\n                case TouchRoute.UiRegion:",
     "ModeB_PipNeverProducesAWorldTap_NoMatterWhatTheThumbDoes"),
    ("R4", "不回收消失的手指（槽位洩漏）", INPUT + "TouchGestureRouter.cs",
     "if (_slotUsed[i] && !_slotSeen[i]) CancelTouch(i);", "if (false) CancelTouch(i);",
     "FingerVanishingWithoutEnded_FreesItsSlot_SoSlotsNeverLeak"),
    ("N1", "延遲注入形同虛設（事件立即到期）", LOGIC + "DelayedEventQueue.cs",
     "double due = now + (delaySeconds > 0.0 ? delaySeconds : 0.0);", "double due = now;",
     "Event_IsNeverDeliveredBeforeItsDelayElapses"),
    ("N2", "延遲佇列後進先出（後發的指令先到）", LOGIC + "DelayedEventQueue.cs",
     "            item = _items[_head];\n            _items[_head] = default; // 釋放可能持有的物件引用\n"
     "            _head = (_head + 1) % _items.Length;\n            _count--;\n            return true;",
     "            int last = (_head + _count - 1) % _items.Length;\n            item = _items[last];\n"
     "            _items[last] = default;\n            _count--;\n            return true;",
     "Order_IsPreserved_EvenWhenALaterEventDrawsAShorterDelay"),
    ("N3", "延遲佇列滿了就丟事件（吃指令）", LOGIC + "DelayedEventQueue.cs",
     "                evicted = _items[_head];\n", "",
     "WhenFull_TheOldestEventIsHandedBack_NothingIsEverDropped"),
    ("H1", "重震也被疲勞節流", LOGIC + "HapticFatiguePolicy.cs",
     "if (cue == HapticCue.CadenceDash || cue == HapticCue.WallBreak) return HapticStrength.Heavy;",
     "if (cue == HapticCue.WallBreak) return HapticStrength.Heavy;",
     "DashAndWallBreak_AreAlwaysHeavy_NeverThrottled"),
    ("H2", "普攻輕震永不靜音", LOGIC + "HapticFatiguePolicy.cs",
     "return _consecutiveBasicHits <= LightPulsesBeforeMute ? HapticStrength.Light : HapticStrength.None;",
     "return HapticStrength.Light;",
     "BasicAttacks_BuzzLightlyThreeTimes_ThenGoQuiet_UntilThePlayerRests"),
    ("H3", "停手後疲勞不重置", LOGIC + "HapticFatiguePolicy.cs",
     "if (_hasHitBefore && now - _lastBasicHitTime >= ResetAfterIdleSeconds) _consecutiveBasicHits = 0;", "",
     "BasicAttacks_BuzzLightlyThreeTimes_ThenGoQuiet_UntilThePlayerRests"),
    ("U1", "符印輕點滲透成點地（Phase 2：阻斷符印事件向下滲透）", INPUT + "TouchGestureRouter.cs",
     "                case RuneGestureOutcome.QuickCast: _sink.OnRuneQuickCast(); break;",
     "                case RuneGestureOutcome.QuickCast: _sink.OnRuneQuickCast(); _sink.OnWorldTap(0f, 0f); break;",
     "TapOnRune_QuickCastsExactlyOnce_AndNeverReachesTheWorld"),
    ("U2", "符印區不分流（手指落到世界層）", INPUT + "InputRoutingManager.cs",
     "            if (_hasRuneZone && _runeZone.Contains(x, y))\n                return TouchRoute.Rune;\n", "",
     "TapOnRune_QuickCastsExactlyOnce_AndNeverReachesTheWorld"),
    ("U4", "滑回原點鬆手仍然成牆", LOGIC + "RuneGestureTracker.cs",
     "            if (InsideOrigin) return RuneGestureOutcome.Cancelled;\n",
     "",
     "DragThenSlideBackToOrigin_Cancels"),
    ("U13", "滑回原點時不亮取消旗標（虛影不會提示玩家此刻放手＝取消）", LOGIC + "RuneGestureTracker.cs",
     "public bool CancelArmed => Held && Dragging && InsideOrigin;",
     "public bool CancelArmed => false;",
     "DragThenSlideBackToOrigin_Cancels"),
    ("U5", "還沒拖曳就被系統中斷卻放出極速石牆", LOGIC + "RuneGestureTracker.cs",
     "return Dragging ? RuneGestureOutcome.Cancelled : RuneGestureOutcome.None;",
     "return Dragging ? RuneGestureOutcome.Cancelled : RuneGestureOutcome.QuickCast;",
     "SystemCancelDuringDrag_Cancels_AndBeforeDragStaysSilent"),
    ("U6", "符印可被兩根手指同時持有", INPUT + "TouchGestureRouter.cs",
     "if (_rune.Held) _slotRoute[slot] = TouchRoute.Rejected; // 符印一次只認一根手指\n                    else _rune.Begin(touchId, x, y, now);",
     "_rune.Begin(touchId, x, y, now);",
     "WhileRuneIsHeld_SecondFingerOnRuneIsIgnored_AndWorldTapsStillWork"),
    ("W1", "石牆壽命不倒數（永久水泥牆）", LOGIC + "RuneWallLogic.cs",
     "            RemainingLifespan -= deltaSeconds;\n", "",
     "Wall_LivesForFiveSeconds"),
    ("W2", "第 6 發以後穿透仍不衰減", LOGIC + "RuneWallLogic.cs",
     "damageMultiplier = PenetrationCount <= _tuning.UndecayedPenetrations ? 1f : _tuning.DecayedDamageMultiplier;",
     "damageMultiplier = 1f;",
     "Penetration_FirstFiveUndecayed_NextFiveAt85Percent_EachShotWearsTheWall"),
    ("W3", "友軍穿透不損耗石牆（無解的自閉陣地）", LOGIC + "RuneWallLogic.cs",
     "            Health -= MaxHealth * _tuning.PenetrationHealthFraction;\n", "",
     "Penetration_FirstFiveUndecayed_NextFiveAt85Percent_EachShotWearsTheWall"),
    ("W4", "全隊石牆上限變 3 面", LOGIC + "RuneCastLogic.cs",
     "_slots = new int[cap < 1 ? 1 : cap];",
     "_slots = new int[cap + 1];",
     "Roster_ThirdWallEvictsTheOldest"),
    ("W5", "已消失的牆仍佔名額", LOGIC + "RuneCastLogic.cs",
     "                RemoveAt(i);\n                return;", "                return;",
     "Roster_ExpiredWallsFreeTheirSeat"),
    ("W6", "冷卻失效（石牆可連放）", LOGIC + "RuneCastLogic.cs",
     "_readyTime = now + _tuning.CooldownSeconds;", "",
     "Cooldown_BlocksForEightSeconds_ThenReadyAgain"),
    ("W7", "查詢落點也會吃掉冷卻（取消施法被罰冷卻）", LOGIC + "RuneCastLogic.cs",
     "            return TryPlace(posX, posZ, dirX, dirZ, distance, out placement);",
     "            _readyTime = 1e9; return TryPlace(posX, posZ, dirX, dirZ, distance, out placement);",
     "WithoutTryBeginCast_NothingIsConsumed"),
    ("W8", "拉伸量不夾住（牆被丟到射程外）", LOGIC + "RuneCastLogic.cs",
     "float t = distance01 < 0f ? 0f : (distance01 > 1f ? 1f : distance01);",
     "float t = distance01;",
     "DragCast_MapsStretchToTwoThroughEightMetres"),
    ("L1", "按鈕邊距的 16px 下限被拿掉（極低 dpi 時按鈕貼進邊緣死區旁）", INPUT + "RuneButtonLayout.cs",
     "if (margin < MinEdgeMarginPixels) margin = MinEdgeMarginPixels;", "",
     "Layout_OnAnExtremelyLowDpiScreen_FallsBackToTheSixteenPixelFloor"),
    ("W9", "貼身帶失效（貼身放牆又得把手指停在取消圈邊緣）", LOGIC + "RuneCastLogic.cs",
     "if (u < 0f) u = 0f;",
     "u = t;",
     "DragCast_NearBand_HoldsTheMinimumDistanceForTheFirstThirdOfTheStroke"),
    ("U7", "短促輕點的拇指滾動被當成拖曳（按了沒反應）", LOGIC + "RuneGestureTracker.cs",
     "if (InsideOrigin && time - StartTime <= tapMaxSeconds && MaxReach <= tapSlopPx) return RuneGestureOutcome.QuickCast;", "",
     "QuickTapWithThumbRoll_IsStillAQuickCast"),
    ("U8", "只看時間不看位移：快速甩出的拖曳被吞成輕點", LOGIC + "RuneGestureTracker.cs",
     "if (InsideOrigin && time - StartTime <= tapMaxSeconds && MaxReach <= tapSlopPx) return RuneGestureOutcome.QuickCast;",
     "if (InsideOrigin && time - StartTime <= tapMaxSeconds) return RuneGestureOutcome.QuickCast;",
     "ThumbRollForgiveness_DoesNotSwallowDeliberateGestures"),
    ("U10", "快速短距離的方向施放被吞成正前方的極速石牆（方向丟失）", LOGIC + "RuneGestureTracker.cs",
     "if (InsideOrigin && time - StartTime <= tapMaxSeconds && MaxReach <= tapSlopPx) return RuneGestureOutcome.QuickCast;",
     "if (time - StartTime <= tapMaxSeconds && MaxReach <= tapSlopPx) return RuneGestureOutcome.QuickCast;",
     "QuickShortAimedDrag_KeepsItsDirection"),

    # ── 批 2：0.5m 阻擋網格／整合場（PHASE2_BATCH2_PLAN.md §5 V3） ──
    ("G1", "整合場允許斜走切角（Build 端）", LOGIC + "FlowField.cs",
     "                    bool diagonal = NeighborDx[n] != 0 && NeighborDz[n] != 0;",
     "                    bool diagonal = false;",
     "CostAt_MatchesBruteForce_LShapeLayout"),
    ("G2", "阻擋網格引用計數退化成 bool（重疊登記/撤銷會誤判）", LOGIC + "BlockGrid.cs",
     "                    int before = _refCount[idx];\n                    int after = before + delta;\n                    _refCount[idx] = after;",
     "                    int before = _refCount[idx];\n                    int after = delta > 0 ? 1 : 0;\n                    _refCount[idx] = after;",
     "ReferenceCounting_OverlapRelease_VersionOnlyFlipsOnTransition"),
    ("G3", "StampBox 忽略外擴量 inflate", LOGIC + "BlockGrid.cs",
     "            float halfW = halfWidth + inflate;\n            float halfT = halfThickness + inflate;",
     "            float halfW = halfWidth;\n            float halfT = halfThickness;",
     "RegistrationAnchor_BoxSpansExpectedCells_AndRotatesWithNormal"),
    ("G4", "界外 IsBlocked 回 false（漏防呆）", LOGIC + "BlockGrid.cs",
     "            if (cx < 0 || cx >= _columns || cz < 0 || cz >= _rows) return true; // 界外一律 Blocked",
     "            if (cx < 0 || cx >= _columns || cz < 0 || cz >= _rows) return false; // 界外一律 Blocked",
     "StampBoxNearBoundary_DoesNotThrow_PartialRegistration_AndOutOfRangeIsBlocked"),
    ("G5", "視線只查兩端點（supercover 全部跳過）", LOGIC + "BlockGrid.cs",
     "            const double tie = 1e-9;\n            int x = cx0, z = cz0;\n            if (IsBlocked(x, z)) return false;",
     "            const double tie = 1e-9;\n            int x = cx0, z = cz0;\n            return !IsBlocked(cx0, cz0) && !IsBlocked(cx1, cz1);",
     "LineOfSight_GrazingOnlyTheCornerOfABlockedCell_IsBlocked"),
    ("G6", "目的地走不到時仍回傳原目的地（英雄頂牆）", LOGIC + "GridNavigator.cs",
     "                if (_goalField.IsReached(connCx, connCz))",
     "                if (true)",
     "ResolveGoal_DestinationSealedByWalls_SubstitutesNearestReachableCell_ThenOriginalOnceOpened"),
    ("G7", "格子翻轉不加 Version（快取永遠不會重建）", LOGIC + "BlockGrid.cs",
     "                    Version++;\n                    BlockedCount += isBlocked ? 1 : -1;",
     "                    BlockedCount += isBlocked ? 1 : -1;",
     "ReferenceCounting_OverlapRelease_VersionOnlyFlipsOnTransition"),
    ("G8", "delta=-1 不生效（撤銷永遠沒有作用）", LOGIC + "BlockGrid.cs",
     "                    int after = before + delta;",
     "                    int after = delta > 0 ? before + delta : before;",
     "ReferenceCounting_OverlapRelease_VersionOnlyFlipsOnTransition"),

    # ── r1 對抗審查後的修訂（PHASE2_BATCH2_PLAN.md §6） ──
    ("G9", "拿掉「有視線就不碰整合場」的快路（R5／審查 H4：每次下指令都跑一次全場 Dijkstra）",
     LOGIC + "GridNavigator.cs",
     "                if (_grid.HasLineOfSight(fromX, fromZ, destX, destZ))",
     "                if (false)",
     "ResolveGoal_WithLineOfSight_NeverRebuildsTheIntegrationField"),
    ("G10", "引用計數不夾負（M1：撤銷不對稱後留下「存在但不擋路」的格）", LOGIC + "BlockGrid.cs",
     "                    if (after < 0)\n                    {\n                        after = 0;\n"
     "                        _refCount[idx] = 0;\n                        NegativeStampCount++;\n                    }",
     "",
     "StampBox_NegativeReferenceCounts_AreClampedAtZero_AndReported"),
    ("G11", "TryGetNext 允許斜走切角（R7 補的涵蓋缺口：G1 只打 Build 那一份）", LOGIC + "FlowField.cs",
     "                bool diagonal = NeighborDx[n] != 0 && NeighborDz[n] != 0;\n                if (diagonal)\n"
     "                {\n                    if (_grid.IsBlocked(cx + NeighborDx[n], cz)) continue;\n"
     "                    if (_grid.IsBlocked(cx, cz + NeighborDz[n])) continue;\n                }",
     "                bool diagonal = false;",
     "TryGetNext_WalksToGoal_WithStrictlyDecreasingCost_NeverEnteringBlockedOrCuttingCorners"),
    ("G12", "替代點只看離目的地最近、不看英雄在哪（R1／審查 H2：英雄被送到牆的另一側）",
     LOGIC + "GridNavigator.cs",
     "                        if (cost > bestCost) continue;\n"
     "                        if (cost == bestCost && !(distSq < bestDistSq)) continue;",
     "                        if (!(distSq < bestDistSq)) continue;",
     "ResolveGoal_SubstitutePoint_PrefersTheSideTheHeroIsAlreadyOn"),
    ("G13", "goal 格被蓋住仍回 Stuck（M4：呼叫端無聲退回 v0.3.2 頂牆）", LOGIC + "GridNavigator.cs",
     "            if (_grid.IsBlocked(goalCx, goalCz)) return SteerMode.GoalBlocked;",
     "            if (_grid.IsBlocked(goalCx, goalCz)) return SteerMode.Stuck;",
     "Steer_WhenTheResolvedGoalCellGetsCovered_ReportsGoalBlocked_NotStuck"),
    ("G14", "界外目的地不夾進格點（R2／審查 H3：整趟退回 Phase 1）", LOGIC + "BlockGrid.cs",
     "            clampedX = Clamp(x, _originX + _cellSize * 0.5f, _originX + (_columns - 0.5f) * _cellSize);",
     "            clampedX = x;",
     "ClampToGrid_BringsOutOfRangePointsBackOntoTheGrid_AndLeavesInsidePointsAlone"),
    ("G15", "拉直路徑退化成逐格前進（R7 鑑別力缺口：45° 鋸齒）", LOGIC + "GridNavigator.cs",
     "            for (int i = 0; i < _tuning.FollowLookaheadCells; i++)",
     "            for (int i = 0; i < 1; i++)",
     "Steer_LookaheadStraightensThePath_WhileLookaheadOneZigzagsPastTheBudget"),

    # ── 主對話覆核後的更正（PHASE2_BATCH2_PLAN.md §6 R8／R9） ──
    ("G16", "拿掉 DDA 的「走完就停」（R9：兩端點都在格角時會走出格點外，空場誤判成沒視線）",
     LOGIC + "BlockGrid.cs",
     "                if (tMaxX > 1.0 && tMaxZ > 1.0) break;",
     "",
     "LineOfSight_OnAnEmptyGrid_CornerAlignedSegments_AreAlwaysClear"),
    ("G17", "提前跳出後不補檢終點格（R9 的另一半）", LOGIC + "BlockGrid.cs",
     "            return !IsBlocked(cx1, cz1);",
     "            return true;",
     "LineOfSight_WithTheDestinationCellBlocked_IsBlocked_EvenWhenBothEndsSitOnCellCorners"),
    ("G18", "替代點停在第二階段的 W（R1a：少了「成本寬限內取最近」，停點被往英雄方向多拉一格）",
     LOGIC + "GridNavigator.cs",
     "            int costLimit = bestCost + _tuning.SubstituteCostSlack;",
     "            int costLimit = -1;",
     "ResolveGoal_SubstitutePoint_TakesTheCellClosestToTheTap_WithinTheCostSlack"),

    # ── r2 對抗審查後的 v0.4.1（PHASE2_BATCH2_PLAN.md §6 R11） ──
    ("G19", "合併後的候選帶方塊算窄了一格（V11-a 的掃描合併偷掉合法候選）", LOGIC + "GridNavigator.cs",
     "            bandMinCx--; bandMinCz--; bandMaxCx++; bandMaxCz++;",
     "            bandMinCx++; bandMinCz++; bandMaxCx--; bandMaxCz--;",
     "ResolveGoal_OnRandomBoards_MatchesTheIndependentR1aReference_ValueForValue"),

    # ── 批 3：破牆護盾／友軍彈道穿透／點擊挑選（PHASE2_BATCH3_PLAN.md §5 V3） ──
    ("S1", "授予規則的陣營比較恆真（砸自家牆也給盾）", LOGIC + "RockShieldLogic.cs",
     "            return ownerFactionId != attackerFactionId;",
     "            return true;",
     "GrantRule_OnlyAMeleeKillOnAForeignWall_GrantsTheShield"),
    ("S2", "沒打死也給盾", LOGIC + "RockShieldLogic.cs",
     "            if (!targetKilled) return false;\n", "",
     "GrantRule_OnlyAMeleeKillOnAForeignWall_GrantsTheShield"),
    ("S3", "打死的不是石牆也給盾（木樁也算）", LOGIC + "RockShieldLogic.cs",
     "            if (!targetIsWall) return false;\n", "",
     "GrantRule_OnlyAMeleeKillOnAForeignWall_GrantsTheShield"),
    ("S4", "擁有者不明改成 fail-open（不明就放行）", LOGIC + "RockShieldLogic.cs",
     "            if (!ownerKnown) return false;\n", "",
     "GrantRule_OnlyAMeleeKillOnAForeignWall_GrantsTheShield"),
    ("S5", "護盾重複取得改成疊加（150 變 300）", LOGIC + "RockShieldLogic.cs",
     "            _amount = _tuning.ShieldAmount;",
     "            _amount += _tuning.ShieldAmount;",
     "RepeatedGrant_RefreshesBackToFull_AndNeverStacks"),
    ("S6", "護盾倒數不遞減（永久護盾）", LOGIC + "RockShieldLogic.cs",
     "            _remainingSeconds -= deltaSeconds;\n", "",
     "Grant_FillsTheShieldAndTheTimer_AndItExpiresWhenTheTimerRunsOut"),
    ("S7", "重複取得不刷新倒數（護盾值滿了卻馬上到期）", LOGIC + "RockShieldLogic.cs",
     "            _remainingSeconds = _tuning.ShieldDurationSeconds;\n", "",
     "RepeatedGrant_RefreshesBackToFull_AndNeverStacks"),
    ("S8", "Absorb 不扣護盾（無限吸收）", LOGIC + "RockShieldLogic.cs",
     "            _amount -= absorbed;\n", "",
     "Absorb_EatsDamageUntilTheShieldRunsOut_ThenLetsTheRestThrough"),
    ("S9", "沒有護盾時也把傷害吞掉", LOGIC + "RockShieldLogic.cs",
     "            if (!IsActive) return incomingDamage;",
     "            if (!IsActive) return 0f;",
     "AnInactiveShield_AbsorbsNothing"),
    ("F1", "掃掠排序反向（遠的先結算）", LOGIC + "ProjectileFlightLogic.cs",
     "            if (a.Distance > b.Distance) return true;\n            if (a.Distance < b.Distance) return false;",
     "            if (a.Distance > b.Distance) return false;\n            if (a.Distance < b.Distance) return true;",
     "SortByDistance_SortsAscending_BreaksTiesByLowerId_AndLeavesTheTailAlone"),
    ("F2", "同距離不看 Id（排序不決定性）", LOGIC + "ProjectileFlightLogic.cs",
     "            return a.Id > b.Id;", "            return false;",
     "SortByDistance_SortsAscending_BreaksTiesByLowerId_AndLeavesTheTailAlone"),
    ("F3", "HasPenetrated 恆假（一發子彈重複吃掉同一面牆的額度）", LOGIC + "ProjectileFlightLogic.cs",
     "            for (int i = 0; i < _penetratedCount; i++)\n"
     "                if (_penetratedWallIds[i] == wallId) return true;\n            return false;",
     "            return false;",
     "RecordPenetration_CountsEachWallOnce_AndMultipliesAcrossDifferentWalls"),
    ("F4", "多面牆的倍率覆寫而非連乘", LOGIC + "ProjectileFlightLogic.cs",
     "            _damageMultiplier *= multiplier;",
     "            _damageMultiplier = multiplier;",
     "RecordPenetration_CountsEachWallOnce_AndMultipliesAcrossDifferentWalls"),
    ("F5", "Reset 不清穿透名冊（池裡取回來的子彈記得上一發穿過的牆）", LOGIC + "ProjectileFlightLogic.cs",
     "            _penetratedCount = 0;\n            _damageMultiplier = 1f;",
     "            _damageMultiplier = 1f;",
     "Reset_ClearsTheMultiplierAndThePenetrationRecord"),
    ("F6", "掃掠長度忽略 deltaTime（穿隧防線失效）", LOGIC + "ProjectileFlightLogic.cs",
     "            return speed * deltaSeconds;", "            return speed;",
     "StepLength_AtThirtyFps_ExceedsTheWallThickness_ButAtOneTwentyFpsItDoesNot"),
    ("T1", "點擊不跳過己方石牆（點自家牆變成砍自家牆）", LOGIC + "TapPickLogic.cs",
     "                if (ownWall[i]) continue;\n", "",
     "SelectNearestAcceptable_SkipsOwnWalls_AndTakesTheNearestOfTheRest"),
    ("T2", "跳過己方牆之後取最遠的命中", LOGIC + "TapPickLogic.cs",
     "                if (best >= 0 && distances[i] >= bestDistance) continue;",
     "                if (best >= 0 && distances[i] <= bestDistance) continue;",
     "SelectNearestAcceptable_SkipsOwnWalls_AndTakesTheNearestOfTheRest"),
    ("T3", "全部被跳過時回索引 0 而不是 -1（憑空點到第一個命中）", LOGIC + "TapPickLogic.cs",
     "            int best = -1;", "            int best = 0;",
     "SelectNearestAcceptable_ReturnsMinusOne_WhenEverythingIsSkippedOrThereIsNothing"),

    # ── 批 4：三大元素反應（PHASE2_BATCH4_PLAN.md §5 V3） ──
    ("E1", "水域半徑漂移（3 → 5）", LOGIC + "ElementTuning.cs",
     "public float WaterRadius = 3f;", "public float WaterRadius = 5f;",
     "Rock_LandingZeroPointOneMetreOutsideWater_MakesNothing"),
    ("E2", "縛足時長漂移（1.2 → 2）", LOGIC + "ElementTuning.cs",
     "public float RootDurationSeconds = 1.2f;", "public float RootDurationSeconds = 2f;",
     "AtOnePointOneNineSeconds_StillRooted_AtOnePointTwoOne_ItMovesAtSixtyFivePercent"),
    ("E3", "流沙減速倍率失效（0.65 → 1）", LOGIC + "ElementTuning.cs",
     "public float QuicksandSlowMultiplier = 0.65f;", "public float QuicksandSlowMultiplier = 1f;",
     "Entering_RootsForOnePointTwoSeconds_ThenSlowsToSixtyFivePercent"),
    ("E4", "顯影時長漂移（1.5 → 3）", LOGIC + "ElementTuning.cs",
     "public float RevealDurationSeconds = 1.5f;", "public float RevealDurationSeconds = 3f;",
     "AtOnePointFourNineSeconds_StillRevealed_AtOnePointFiveOne_ConcealedAgain"),
    ("E5", "晶塔引導係數失效（0.5 → 1）", LOGIC + "ElementTuning.cs",
     "public float SteamChannelSpeedMultiplier = 0.5f;", "public float SteamChannelSpeedMultiplier = 1f;",
     "ChannelSpeedMultiplier_IsHalvedInsideSteam_AndFullOutside"),
    ("E6", "火浪扇形角度漂移（60 → 120）", LOGIC + "ElementTuning.cs",
     "public float FirestormAngleDegrees = 60f;", "public float FirestormAngleDegrees = 120f;",
     "IsInsideSector_AcceptsOneDegreeInside_AndRejectsOneDegreeOutside"),
    ("E7", "火浪扇形射程漂移（6 → 12）", LOGIC + "ElementTuning.cs",
     "public float FirestormRangeMeters = 6f;", "public float FirestormRangeMeters = 12f;",
     "IsInsideSector_AcceptsAtRange_AndRejectsZeroPointOneMetreBeyond"),
    ("E8", "火浪傷害倍率失效（1.5 → 1）", LOGIC + "ElementTuning.cs",
     "public float FirestormDamageMultiplier = 1.5f;", "public float FirestormDamageMultiplier = 1f;",
     "Wind_SweepingABurningZone_MakesAFirestorm_AndConsumesTheBurningZone"),
    ("E9", "燃燒 DoT 每秒傷害漂移（20 → 10）", LOGIC + "ElementTuning.cs",
     "public float BurnDamagePerSecond = 20f;", "public float BurnDamagePerSecond = 10f;",
     "BurningZone_OverFourSeconds_DealsEightyDamageInTotal"),
    ("E10", "燃燒區壽命漂移（4 → 8）", LOGIC + "ElementTuning.cs",
     "public float BurnDurationSeconds = 4f;", "public float BurnDurationSeconds = 8f;",
     "BurningZone_OverFourSeconds_DealsEightyDamageInTotal"),
    ("E11", "爆沸傷害漂移（80 → 40）", LOGIC + "ElementTuning.cs",
     "public float BoilDamage = 80f;", "public float BoilDamage = 40f;",
     "Fire_HittingHostileQuicksand_Boils_AndTerminatesTheQuicksand"),
    ("E12", "火直傷歸零（40 → 0）", LOGIC + "ElementTuning.cs",
     "public float FireDirectDamage = 40f;", "public float FireDirectDamage = 0f;",
     "Fire_OnOpenGround_DealsDirectDamage_AndLeavesABurningZone"),
    ("E13", "流沙壽命漂移（3.5 → 7）", LOGIC + "ElementTuning.cs",
     "public float QuicksandDurationSeconds = 3.5f;", "public float QuicksandDurationSeconds = 7f;",
     "Tick_ExpiresAQuicksandAtThreePointFive_AndSteamAtThree"),
    ("E14", "水域壽命漂移（6 → 12）", LOGIC + "ElementTuning.cs",
     "public float WaterDurationSeconds = 6f;", "public float WaterDurationSeconds = 12f;",
     "Tick_ExpiresAWaterZoneExactlyAtSixSeconds"),
    ("E15", "施放冷卻失效（5 → 0）", LOGIC + "ElementTuning.cs",
     "public float SkillCooldownSeconds = 5f;", "public float SkillCooldownSeconds = 0f;",
     "Cast_IsRejectedDuringTheFiveSecondCooldown_AndAcceptedAtFiveSeconds"),
    ("E16", "Combo 頓挫打進 Clamp 外（45 → 450）", LOGIC + "ElementTuning.cs",
     "public float ComboHitstopMs = 45f;", "public float ComboHitstopMs = 450f;",
     "ComboHitstop_IsStrictlyInsideTheClampWindow_SoTheValueIsNotSilentlyRewritten"),
    ("E17", "陣營方向反轉（!= → ==）", LOGIC + "ElementReactionLogic.cs",
     "bool isRescue = castFactionId != quicksand.FactionId;", "bool isRescue = castFactionId == quicksand.FactionId;",
     "Fire_HittingFriendlyQuicksand_Rescues_AndTerminatesTheQuicksand"),
    ("E18", "陣營判定恆真（整個條件 → true）", LOGIC + "ElementReactionLogic.cs",
     "bool isRescue = castFactionId != quicksand.FactionId;", "bool isRescue = true;",
     "Fire_HittingHostileQuicksand_Boils_AndTerminatesTheQuicksand"),
    ("E19", "優先序倒過來（先查 Water 再查 Quicksand）", LOGIC + "ElementReactionLogic.cs",
     "            int quicksandId = field.FindNearestContaining(x, z, ElementZoneKind.Quicksand);\n            if (quicksandId >= 0) return ResolveFireOnQuicksand(castFactionId, quicksandId, field, tuning);\n\n            int waterId = field.FindNearestContaining(x, z, ElementZoneKind.Water);\n            if (waterId >= 0) return ResolveFireOnWater(castFactionId, waterId, field, tuning);",
     "            int waterId = field.FindNearestContaining(x, z, ElementZoneKind.Water);\n            if (waterId >= 0) return ResolveFireOnWater(castFactionId, waterId, field, tuning);\n\n            int quicksandId = field.FindNearestContaining(x, z, ElementZoneKind.Quicksand);\n            if (quicksandId >= 0) return ResolveFireOnQuicksand(castFactionId, quicksandId, field, tuning);",
     "Fire_OverlappingQuicksandAndWater_PicksQuicksandOnly"),
    ("E20", "蒸氣反應也留燃燒區（NewZoneKindCode 改 Burning）", LOGIC + "ElementReactionLogic.cs",
     "outcome.NewZoneKindCode = (int)ElementZoneKind.Steam;", "outcome.NewZoneKindCode = (int)ElementZoneKind.Burning;",
     "Fire_HittingWater_MakesSteam_AndLeavesNoBurningZone"),
    ("E21", "流沙取水域陣營而非石牆陣營", LOGIC + "ElementReactionLogic.cs",
     "int newQuicksandFactionId = castFactionId;", "int newQuicksandFactionId = water.FactionId;",
     "Quicksand_TakesTheFactionOfTheWall_WhenWaterAndWallDisagree"),
    ("E22", "風沒掃到燃燒區也給 AoeDamage", LOGIC + "ElementReactionLogic.cs",
     "if (burningId < 0) return None();", "if (burningId < 0) { }",
     "Wind_SweepingABurningZone_MakesAFirestorm_AndConsumesTheBurningZone"),
    ("E23", "IsHostile 恆真", LOGIC + "ElementReactionLogic.cs",
     "return castFactionId != targetFactionId;", "return true;",
     "IsHostile_IsTrueAcrossFactions_AndFalseWithinOne"),
    ("E24", "圓形 <= 改 <（排除邊界）", LOGIC + "ElementGeometry.cs",
     "return (dx * dx + dz * dz) <= radiusSq;", "return (dx * dx + dz * dz) < radiusSq;",
     "IsInsideCircle_IncludesTheBoundary_AndExcludesAPointJustOutside"),
    ("E25", "扇形忽略角度（只比距離）", LOGIC + "ElementGeometry.cs",
     "return dot >= cosHalfAngle;", "return true;",
     "IsInsideSector_AcceptsOneDegreeInside_AndRejectsOneDegreeOutside"),
    ("E26", "半角當全角（totalAngle * 0.5f → totalAngle）", LOGIC + "ElementGeometry.cs",
     "double halfAngleRad = totalAngleDegrees * 0.5 * (Math.PI / 180.0);", "double halfAngleRad = totalAngleDegrees * (Math.PI / 180.0);",
     "IsInsideSector_AcceptsOneDegreeInside_AndRejectsOneDegreeOutside"),
    ("E27", "CollectInsideCircle 不檢查 outIndices 容量", LOGIC + "ElementGeometry.cs",
     "for (int i = 0; i < count && written < outIndices.Length; i++)", "for (int i = 0; i < count; i++)",
     "CollectInsideCircle_ReturnsIndicesInAscendingOrder_AndStopsAtBufferCapacity"),
    ("E28", "池滿時回 -1（不擠）", LOGIC + "ElementZoneField.cs",
     "if (slot < 0) slot = FindSlotWithLeastTimeLeft();", "if (slot < 0) return -1;",
     "Spawn_WhenTheFieldIsFull_EvictsTheZoneWithTheLeastTimeLeft"),
    ("E29", "擠掉『剩餘時間最長』者", LOGIC + "ElementZoneField.cs",
     "if (_zones[i].RemainingSeconds < _zones[best].RemainingSeconds) best = i;", "if (_zones[i].RemainingSeconds > _zones[best].RemainingSeconds) best = i;",
     "Spawn_WhenTheFieldIsFull_EvictsTheZoneWithTheLeastTimeLeft"),
    ("E30", "FindNearestContaining 回第一個命中而非最近", LOGIC + "ElementZoneField.cs",
     "if (bestId != -1 && distSq > bestDistSq) continue;", "if (bestId != -1) continue;",
     "Fire_OverlappingTwoWaterZones_PicksTheNearestCentre"),
    ("E31", "拿掉 RootedByZoneId 比對（每次進入都縛足）", LOGIC + "QuicksandStatusLogic.cs",
     "if (insideZoneId != _rootedByZoneId)", "if (true)",
     "LeavingAndReentering_TheSameQuicksand_DoesNotRootAgain"),
    ("E32", "離開後仍保留 0.65 減速", LOGIC + "QuicksandStatusLogic.cs",
     "                _currentZoneId = -1;\n                _rootRemainingSeconds = 0f;\n                return;", "                _rootRemainingSeconds = 0f;\n                return;",
     "LeavingTheQuicksand_RestoresFullSpeedImmediately"),
    ("E33", "遮蔽忽略『攻擊者同霧』", LOGIC + "SteamConcealmentLogic.cs",
     "return targetInsideSteam && !attackerInsideSameSteam && !targetRevealed;", "return targetInsideSteam && !targetRevealed;",
     "TargetInsideSteam_IsConcealed_FromAnAttackerOutside_ButNotFromOneInTheSameSteam"),
    ("E34", "遮蔽忽略顯影旗標", LOGIC + "SteamConcealmentLogic.cs",
     "return targetInsideSteam && !attackerInsideSameSteam && !targetRevealed;", "return targetInsideSteam && !attackerInsideSameSteam;",
     "AtOnePointFourNineSeconds_StillRevealed_AtOnePointFiveOne_ConcealedAgain"),
    ("E35", "NotifyDamaged 改成疊加", LOGIC + "SteamConcealmentLogic.cs",
     "_revealRemainingSeconds = _tuning.RevealDurationSeconds;", "_revealRemainingSeconds += _tuning.RevealDurationSeconds;",
     "BeingDamagedAgain_RefreshesTheRevealToOnePointFive"),
    ("E36", "冷卻中按下也重置計時", LOGIC + "ElementCastCooldowns.cs",
     "if (nowSeconds < _readyAtSeconds[slot]) return false;", "if (nowSeconds < _readyAtSeconds[slot]) { _readyAtSeconds[slot] = nowSeconds + _tuning.SkillCooldownSeconds; return false; }",
     "Cast_IsRejectedDuringTheFiveSecondCooldown_AndAcceptedAtFiveSeconds"),

    # ── v0.6.1：反應飄字／受困狀態回饋（V061_FEEDBACK_PLAN.md §3 F1-c） ──
    ("C1", "爆沸／救援的飄字索引對調", LOGIC + "ElementCalloutLogic.cs",
     "                case ElementReaction.Boil: return BoilLabelIndex;\n                case ElementReaction.Rescue: return RescueLabelIndex;",
     "                case ElementReaction.Boil: return RescueLabelIndex;\n                case ElementReaction.Rescue: return BoilLabelIndex;",
     "LabelIndexFor_MapsTheFiveReactions_AndReturnsMinusOneForTheRest"),
    ("C2", "空地火也跳字（回 0，與流沙同一個索引）", LOGIC + "ElementCalloutLogic.cs",
     "case ElementReaction.PlainFire: return NoCalloutIndex;", "case ElementReaction.PlainFire: return QuicksandLabelIndex;",
     "LabelIndexFor_MapsTheFiveReactions_AndReturnsMinusOneForTheRest"),
    ("C3", "拿掉縛足優先分支（永遠回 0，ROOTED 再也不會顯示）", LOGIC + "ElementCalloutLogic.cs",
     "            if (isRooted) return RootedStatus;\n            if (speedMultiplier < 1f) return SlowedStatus;\n            return NormalStatus;",
     "            if (speedMultiplier < 1f) return SlowedStatus;\n            return NormalStatus;",
     "HeroStatusIndex_RootedWins_ThenSlowed_ThenNone"),
    ("C4", "減速判準含滿速（<1f 改 <=1f，滿速時誤判成 SLOWED）", LOGIC + "ElementCalloutLogic.cs",
     "if (speedMultiplier < 1f) return SlowedStatus;", "if (speedMultiplier <= 1f) return SlowedStatus;",
     "HeroStatusIndex_RootedWins_ThenSlowed_ThenNone"),

    # ── v0.8.0 Capture Step A（V080_CAPTURE_PLAN.md §3-A V-A27，2026-09-24 凍結） ──
    ('C1', '翻塊用 > 而非 >=', LOGIC + "CaptureMatchLogic.cs",
     '            if (progress >= _tuning.CaptureSeconds)', '            if (progress > _tuning.CaptureSeconds)',
     'VA06_CaptureTakesExactlyFourteenQuarterTicks_OrTwentyEightEighthTicks'),
    ('C2', '爭奪照樣推進（拿掉凍結）', LOGIC + "CaptureMatchLogic.cs",
     '            if (blueCircle != -1 && blueCircle == redCircle)\n            {\n                ContestTickCount++; // 雙方進度都凍結保留，不增加也不歸零\n            }\n            else\n            {\n                ProcessSide(blueCircle, dt, ref _blueTile, ref _blueProgress, BlueFactionId);\n                ProcessSide(redCircle, dt, ref _redTile, ref _redProgress, RedFactionId);\n            }\n', '            if (blueCircle != -1 && blueCircle == redCircle)\n            {\n                ContestTickCount++;\n                ProcessSide(blueCircle, dt, ref _blueTile, ref _blueProgress, BlueFactionId);\n                ProcessSide(redCircle, dt, ref _redTile, ref _redProgress, RedFactionId);\n            }\n            else\n            {\n                ProcessSide(blueCircle, dt, ref _blueTile, ref _blueProgress, BlueFactionId);\n                ProcessSide(redCircle, dt, ref _redTile, ref _redProgress, RedFactionId);\n            }\n',
     'VA09_ContestFreezesProgress_IncludingWhenTheOwnerIsDefending'),
    ('C3', '爭奪時歸零', LOGIC + "CaptureMatchLogic.cs",
     '            if (blueCircle != -1 && blueCircle == redCircle)\n            {\n                ContestTickCount++; // 雙方進度都凍結保留，不增加也不歸零\n            }\n            else\n            {\n                ProcessSide(blueCircle, dt, ref _blueTile, ref _blueProgress, BlueFactionId);\n                ProcessSide(redCircle, dt, ref _redTile, ref _redProgress, RedFactionId);\n            }\n', '            if (blueCircle != -1 && blueCircle == redCircle)\n            {\n                ContestTickCount++;\n                _blueProgress = 0f; _blueTile = -1;\n                _redProgress = 0f; _redTile = -1;\n            }\n            else\n            {\n                ProcessSide(blueCircle, dt, ref _blueTile, ref _blueProgress, BlueFactionId);\n                ProcessSide(redCircle, dt, ref _redTile, ref _redProgress, RedFactionId);\n            }\n',
     'VA09_ContestFreezesProgress_IncludingWhenTheOwnerIsDefending'),
    ('C4', '離圈保留進度（不歸零）', LOGIC + "CaptureMatchLogic.cs",
     '            if (circle == -1)\n            {\n                tile = -1;\n                progress = 0f;\n                return;\n            }\n', '            if (circle == -1)\n            {\n                return;\n            }\n',
     'VA07_LeavingTheCircle_ZeroesProgress'),
    ('C5', '忽略受傷（NotifyDamaged 空實作）', LOGIC + "CaptureMatchLogic.cs",
     '        public void NotifyDamaged(int side)\n        {\n            if (side == BlueFactionId)\n            {\n                if (_blueTile != -1) InterruptCount++;\n                _blueTile = -1;\n                _blueProgress = 0f;\n            }\n            else if (side == RedFactionId)\n            {\n                if (_redTile != -1) InterruptCount++;\n                _redTile = -1;\n                _redProgress = 0f;\n            }\n        }\n', '        public void NotifyDamaged(int side)\n        {\n        }\n',
     'VA08_DamageInterruptsOwnSideOnly_AndIsSafeOutsideTheCircle'),
    ('C6', '翻塊時重置計分時鐘', LOGIC + "CaptureMatchLogic.cs",
     '            if (progress >= _tuning.CaptureSeconds)\n            {\n                _ownership[circle] = factionId;\n                progress = 0f;\n                tile = -1;\n                FlipCount++;\n            }\n', '            if (progress >= _tuning.CaptureSeconds)\n            {\n                _ownership[circle] = factionId;\n                progress = 0f;\n                tile = -1;\n                FlipCount++;\n                _scoreClock = 0f;\n            }\n',
     'VA13_FlipHappensBeforeScoring_AndDoesNotResetTheScoreClock'),
    ('C7', '先計分再翻塊（ProcessScoring 搬到最前面）', LOGIC + "CaptureMatchLogic.cs",
     '            ProcessChannels(blueCircle, redCircle, dt);   // ③ 引導／爭奪／翻塊\n\n            // 復活地點要看「已經處理過本 tick 翻塊之後」的歸屬，所以快照必須排在 ProcessChannels 之後\n            // （這兩行的相對位置就是 E20「同一 tick 先翻塊再判定」的語意本體，順序不得調換）。\n            bool blueBaseOwnedByBlue = _ownership[HexBoardLayout.BlueBaseTile] == BlueFactionId;\n            bool redBaseOwnedByRed = _ownership[HexBoardLayout.RedBaseTile] == RedFactionId;\n            ProcessKnockouts(dt, blueBaseOwnedByBlue, redBaseOwnedByRed);   // ④ 倒地倒數與復活地點\n\n            ProcessScoring(dt);   // ⑤ 計分時鐘 ⑥ 勝負\n', '            ProcessScoring(dt);   // ⑤ 計分時鐘 ⑥ 勝負\n\n            ProcessChannels(blueCircle, redCircle, dt);   // ③ 引導／爭奪／翻塊\n\n            bool blueBaseOwnedByBlue = _ownership[HexBoardLayout.BlueBaseTile] == BlueFactionId;\n            bool redBaseOwnedByRed = _ownership[HexBoardLayout.RedBaseTile] == RedFactionId;\n            ProcessKnockouts(dt, blueBaseOwnedByBlue, redBaseOwnedByRed);   // ④ 倒地倒數與復活地點\n',
     'VA13_FlipHappensBeforeScoring_AndDoesNotResetTheScoreClock'),
    ('C11', '同一 tick 先復活後翻塊（ProcessKnockouts 搬到 ProcessChannels 之前）', LOGIC + "CaptureMatchLogic.cs",
     '            ProcessChannels(blueCircle, redCircle, dt);   // ③ 引導／爭奪／翻塊\n\n            // 復活地點要看「已經處理過本 tick 翻塊之後」的歸屬，所以快照必須排在 ProcessChannels 之後\n            // （這兩行的相對位置就是 E20「同一 tick 先翻塊再判定」的語意本體，順序不得調換）。\n            bool blueBaseOwnedByBlue = _ownership[HexBoardLayout.BlueBaseTile] == BlueFactionId;\n            bool redBaseOwnedByRed = _ownership[HexBoardLayout.RedBaseTile] == RedFactionId;\n            ProcessKnockouts(dt, blueBaseOwnedByBlue, redBaseOwnedByRed);   // ④ 倒地倒數與復活地點\n\n            ProcessScoring(dt);   // ⑤ 計分時鐘 ⑥ 勝負\n', '            bool blueBaseOwnedByBlue = _ownership[HexBoardLayout.BlueBaseTile] == BlueFactionId;\n            bool redBaseOwnedByRed = _ownership[HexBoardLayout.RedBaseTile] == RedFactionId;\n            ProcessKnockouts(dt, blueBaseOwnedByBlue, redBaseOwnedByRed);   // ④ 倒地倒數與復活地點\n\n            ProcessChannels(blueCircle, redCircle, dt);   // ③ 引導／爭奪／翻塊\n\n            ProcessScoring(dt);   // ⑤ 計分時鐘 ⑥ 勝負\n',
     'VA17_RespawnLocation_HomeUnlessTheBaseWasCaptured'),
    ('C10', '在倒地當下決定復活點（藍方一律回家）', LOGIC + "CaptureMatchLogic.cs",
     '                    _bluePendingRespawnX = blueBaseOwnedByBlue ? _tuning.BlueHomeRespawnX : _tuning.BlueEdgeRespawnX;\n                    _bluePendingRespawnZ = blueBaseOwnedByBlue ? _tuning.BlueHomeRespawnZ : _tuning.BlueEdgeRespawnZ;\n', '                    _bluePendingRespawnX = _tuning.BlueHomeRespawnX;\n                    _bluePendingRespawnZ = _tuning.BlueHomeRespawnZ;\n',
     'VA17_RespawnLocation_HomeUnlessTheBaseWasCaptured'),
    ('C8', '勝負用 > 1000 而非 >= 1000', LOGIC + "CaptureMatchLogic.cs",
     '                bool blueWon = BlueScore >= _tuning.WinScore;\n                bool redWon = RedScore >= _tuning.WinScore;\n', '                bool blueWon = BlueScore > _tuning.WinScore;\n                bool redWon = RedScore > _tuning.WinScore;\n',
     'VA14_WinIsDetectedOnTheExactPulseTick_NotClampedAtTheThreshold'),
    ('C9', '同分（含雙方都達標）時藍方優先', LOGIC + "CaptureMatchLogic.cs",
     '                    if (blueWon && redWon)\n                    {\n                        Result = BlueScore > RedScore ? CaptureMatchResult.BlueWins\n                                : RedScore > BlueScore ? CaptureMatchResult.RedWins\n                                : CaptureMatchResult.Draw;\n                    }\n', '                    if (blueWon && redWon)\n                    {\n                        Result = CaptureMatchResult.BlueWins;\n                    }\n',
     'VA15_BothCrossingTheLineOnTheSamePulse_HigherScoreWins'),
    ('C12', '屍體算在場（拿掉倒地強制 -1）', LOGIC + "CaptureMatchLogic.cs",
     '            int blueCircle = _blueKnockedOut ? -1 : HexBoardLayout.CircleAt(heroX, heroZ, _tuning.CircleRadius);\n            int redCircle = _redKnockedOut ? -1 : HexBoardLayout.CircleAt(opponentX, opponentZ, _tuning.CircleRadius);\n', '            int blueCircle = HexBoardLayout.CircleAt(heroX, heroZ, _tuning.CircleRadius);\n            int redCircle = HexBoardLayout.CircleAt(opponentX, opponentZ, _tuning.CircleRadius);\n',
     'VA11_TheKnockedOutSide_DoesNotCountAsPresent'),
    ('C13', '平手取索引大（TileAt 反向迴圈）', LOGIC + "HexBoardLayout.cs",
     '        public static int TileAt(float x, float z)\n        {\n            for (int i = 0; i < TileCount; i++)\n            {\n                if (ContainsPoint(CenterXs[i], CenterZs[i], x, z)) return i;\n            }\n            return -1;\n        }\n', '        public static int TileAt(float x, float z)\n        {\n            for (int i = TileCount - 1; i >= 0; i--)\n            {\n                if (ContainsPoint(CenterXs[i], CenterZs[i], x, z)) return i;\n            }\n            return -1;\n        }\n',
     'VA03_TileAt_BoundaryInclusive_SmallestIndexOnOverlap'),
    ('C14', '追打沒有遲滯（一律用起追門檻）', LOGIC + "CaptureOpponentPolicy.cs",
     '                float thresholdSq = wasChasingLastFrame\n                    ? tuning.ChaseGiveUpDistance * tuning.ChaseGiveUpDistance\n                    : tuning.ChaseStartDistance * tuning.ChaseStartDistance;\n', '                float thresholdSq = tuning.ChaseStartDistance * tuning.ChaseStartDistance;\n',
     'VA22_ChaseStartAndGiveUp_HaveHysteresis_AndNeverChaseAKnockedOutHero'),
    ('C15', '比分用 IntStringCache（1000 會變 999）', LOGIC + "CaptureHudLabels.cs",
     '        public static string Score(int value)\n        {\n            if (value < 0) value = 0;\n            if (value > MaxScore) value = MaxScore;\n            return ScoreTable[value];\n        }\n', '        public static string Score(int value)\n        {\n            return IntStringCache.Get(value);\n        }\n',
     'VA23_ScoreTable_CoversZeroToTwelveOverOneThousand'),
    ('C16', 'MatchGate 只看單挑狀態（拿掉佔領狀態分支）', LOGIC + "MatchGate.cs",
     '        public static MatchGateDecision Evaluate(DuelRoundState duelState, CaptureMatchState captureState, bool heroAlive)\n        {\n            if (captureState == CaptureMatchState.Lobby)\n            {\n                return new MatchGateDecision(false, false, CaptureTapAction.OpenCapture, CaptureButtonAction.ExitCaptureMode);\n            }\n            if (captureState == CaptureMatchState.Active)\n            {\n                return new MatchGateDecision(true, !heroAlive, CaptureTapAction.None, CaptureButtonAction.Invalid);\n            }\n            if (captureState == CaptureMatchState.Ended)\n            {\n                return new MatchGateDecision(true, true, CaptureTapAction.None, CaptureButtonAction.Invalid);\n            }\n\n            // captureState == Off：沿用 v0.7.0 單挑狀態的真值表（R1～R3 原樣）。\n            switch (duelState)\n', '        public static MatchGateDecision Evaluate(DuelRoundState duelState, CaptureMatchState captureState, bool heroAlive)\n        {\n            switch (duelState)\n',
     'VA20_MatchGate_TruthTable'),
    ('C17', '邊界用嚴格不等號（CircleAt 的 <= 改 <）', LOGIC + "HexBoardLayout.cs",
     '                if (dx * dx + dz * dz <= radiusSq) return i;\n', '                if (dx * dx + dz * dz < radiusSq) return i;\n',
     'VA04_CircleAt_BoundaryInclusive'),

    # ── v0.8.0 Capture Step A 審稿修補（2026-09-24 主對話裁定 1/2/3） ──
    ('C18', '拿掉己方塊的排除（單獨守自家塔又空轉引導）', LOGIC + "CaptureMatchLogic.cs",
     '            if (circle == -1 || _ownership[circle] == factionId)\n            {\n                tile = -1;\n                progress = 0f;\n                return;\n            }\n', '            if (circle == -1)\n            {\n                tile = -1;\n                progress = 0f;\n                return;\n            }\n',
     'ReviewFix1_StandingAloneOnYourOwnBase_DoesNotChannel_ThenCapturingElsewhereStillWorks'),
    ('C13b', '平手取索引大（SelectTargetTile 改用 <=，後面的同分覆寫前面）', LOGIC + "CaptureOpponentPolicy.cs",
     '                if (best == -1 || distSq < bestDistSq)\n                {\n                    best = i;\n                    bestDistSq = distSq;\n                }\n', '                if (best == -1 || distSq <= bestDistSq)\n                {\n                    best = i;\n                    bestDistSq = distSq;\n                }\n',
     'VA21_SelectTargetTile_NearestNonRedTile_SmallestIndexOnExactTie'),
    ('C17b', '邊界用嚴格不等號（ContainsPoint 的 cross < 0f 改 <= 0f）', LOGIC + "HexBoardLayout.cs",
     '                if (cross < 0f) return false;\n', '                if (cross <= 0f) return false;\n',
     'VA03_TileAt_BoundaryInclusive_SmallestIndexOnOverlap'),
]


def write_text(path, text, crlf):
    if crlf:
        text = text.replace("\n", "\r\n")
    io.open(path, "w", encoding="utf-8", newline="").write(text)


def run_tests():
    build = subprocess.run([DOTNET, "build", PROJ, "--nologo", "--no-incremental", "-v", "q"],
                           capture_output=True, text=True, encoding="utf-8", errors="replace", env=ENV)
    if build.returncode != 0:
        return None, ["<BUILD FAILED>"]
    trx_dir = os.path.join(os.path.dirname(PROJ), "TestResults")
    test = subprocess.run([DOTNET, "test", PROJ, "--nologo", "--no-build", "--logger", "trx;LogFileName=mutation.trx",
                           "--results-directory", trx_dir],
                          capture_output=True, text=True, encoding="utf-8", errors="replace", env=ENV)
    trx = io.open(os.path.join(trx_dir, "mutation.trx"), encoding="utf-8", errors="replace").read()
    failed = sorted(set(re.findall(r'testName="([^"]+)"[^>]*outcome="Failed"', trx)) |
                    set(re.findall(r'outcome="Failed"[^>]*testName="([^"]+)"', trx)))
    total = len(re.findall(r"<UnitTestResult ", trx))
    return total, [name.split(".")[-1] for name in failed]


def main():
    caught = 0
    for code, title, rel, original, broken, must_fail in MUTATIONS:
        path = os.path.join(ROOT, rel)
        raw = io.open(path, encoding="utf-8", newline="").read()
        crlf = "\r\n" in raw  # 記下原檔的行尾格式，還原時照原樣寫回，跑完不弄髒工作區
        source = raw.replace("\r\n", "\n")
        if source.count(original) != 1:
            print("%s  SKIP（找不到唯一的原文，突變定義已過期）：%s" % (code, title))
            continue
        try:
            write_text(path, source.replace(original, broken), crlf)
            total, failed = run_tests()
        finally:
            write_text(path, source, crlf)

        ok = must_fail in failed
        caught += ok
        print("%s  %s  %s -> %d 個測試變紅%s" % (code, "CAUGHT" if ok else "MISSED", title, len(failed),
                                            "" if ok else "（預期 %s 要紅）" % must_fail))
        for name in failed:
            print("        RED %s" % name)

    total, failed = run_tests()
    clean = total is not None and not failed
    print("\n還原後：%s 個測試，%d 個失敗" % (total, len(failed)))
    print("突變被抓到：%d / %d" % (caught, len(MUTATIONS)))
    result = caught == len(MUTATIONS) and clean
    print("RESULT: " + ("ALL MUTATIONS CAUGHT" if result else "FAILED"))
    return 0 if result else 1


if __name__ == "__main__":
    sys.exit(main())
